server:
  port: 9092

spring:
  profiles:
    active: test

  datasource:
    name: dataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:qst;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.springframework.data.solr.core.SolrTemplate: debug

graphql:
  spqr:
    gui:
      enabled: true
